version: '3.7'
services:
  url-shortener-server:
    restart: always
    container_name: encurtador-url
    env_file:
      - .env
    environment: 
      - NODE_ENV=production
    build:
      context: ./
    image: encurtador-url
    ports:
      - "8080:8080"